[tool.black]
line-length = 88
target-version = ["py310"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
known_local_folder = ["database", "models", "schemas"]

[tool.flake8]
max-line-length = 88
application-import-names = ["database", "models", "schemas"]

extend-ignore = [
    "E203",  # конфликтует с black (срезы)
    "W503",  # конфликтует с black (разрывы строк перед оператором)
]
exclude = [
    "__pycache__",
    ".git",
    ".venv",
    ".mypy_cache",
]
