[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
force_sort_within_sections = true
combine_as_imports = true
known_local_folder = ["database", "models", "schemas"]

[tool.mypy]
ignore_missing_imports = true
